-- Table: public.Films

-- DROP TABLE IF EXISTS public."Films";

CREATE TABLE IF NOT EXISTS public."Films"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "FilmName" text COLLATE pg_catalog."default" NOT NULL,
    "Country" text COLLATE pg_catalog."default" NOT NULL,
    "Director" text COLLATE pg_catalog."default",
    "Genre" text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "PK_Films" PRIMARY KEY ("Id")
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."Films"
    OWNER to postgres;